"""pydantic (record_schema) → TypeScript types.

Single source of truth is record_schema/models.py. Run ``make codegen`` after any change.
Output: packages/schema/ts/index.ts (imported by apps/web via the ``@schema`` alias).
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any

from pydantic import BaseModel, TypeAdapter

import record_schema as rs

HERE = Path(__file__).resolve().parent
OUT = HERE / "ts" / "index.ts"

ROOT_MODELS: list[str] = [
    n for n in rs.__all__ if isinstance(getattr(rs, n), type) and issubclass(getattr(rs, n), BaseModel)
]
ROOT_ALIASES: dict[str, Any] = {
    "Lang": rs.Lang,
    "ProvenanceSource": rs.ProvenanceSource,
    "Dimension": rs.Dimension,
    "IncidentKind": rs.IncidentKind,
    "Direction": rs.Direction,
    "Status": rs.Status,
    "Shift": rs.Shift,
    "RouteDecision": rs.RouteDecision,
    "TimelineEntry": rs.TimelineEntry,
    "Document": rs.Document,
}


def ts_literal(v: Any) -> str:
    return json.dumps(v, ensure_ascii=False)


def ref_name(ref: str) -> str:
    return ref.split("/")[-1]


def ts_type(schema: dict[str, Any], defs: dict[str, Any]) -> str:
    if "$ref" in schema:
        return ref_name(schema["$ref"])
    if "const" in schema:
        return ts_literal(schema["const"])
    if "enum" in schema:
        return " | ".join(ts_literal(v) for v in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(ts_type(s, defs) for s in schema["anyOf"])
    if "oneOf" in schema:
        return " | ".join(ts_type(s, defs) for s in schema["oneOf"])
    if "allOf" in schema and len(schema["allOf"]) == 1:
        return ts_type(schema["allOf"][0], defs)
    t = schema.get("type")
    if isinstance(t, list):
        return " | ".join(ts_type({**schema, "type": x}, defs) for x in t)
    if t == "string":
        return "string"
    if t in ("number", "integer"):
        return "number"
    if t == "boolean":
        return "boolean"
    if t == "null":
        return "null"
    if t == "array":
        inner = ts_type(schema.get("items", {}), defs)
        if " | " in inner:
            inner = f"({inner})"
        return f"{inner}[]"
    if t == "object":
        if "properties" in schema:
            return "{ " + "; ".join(prop_lines(schema, defs)) + " }"
        ap = schema.get("additionalProperties")
        if isinstance(ap, dict):
            return f"Record<string, {ts_type(ap, defs)}>"
        return "Record<string, unknown>"
    return "unknown"


def prop_lines(schema: dict[str, Any], defs: dict[str, Any]) -> list[str]:
    # Serialization mode: pydantic always emits every field, so nothing is optional in TS.
    # `| null` still appears for Optional fields.
    lines = []
    for name, prop in schema.get("properties", {}).items():
        opt = ""
        desc = prop.get("description")
        comment = f"/** {desc} */ " if desc else ""
        lines.append(f"{comment}{name}{opt}: {ts_type(prop, defs)}")
    return lines


def emit_interface(name: str, schema: dict[str, Any], defs: dict[str, Any]) -> str:
    doc = schema.get("description")
    head = f"/** {doc} */\n" if doc else ""
    body = "\n".join(f"  {line};" for line in prop_lines(schema, defs))
    return f"{head}export interface {name} {{\n{body}\n}}\n"


def main() -> None:
    defs: dict[str, Any] = {}
    root_schemas: dict[str, Any] = {}
    for name in ROOT_MODELS:
        model = getattr(rs, name)
        s = model.model_json_schema(mode="serialization")
        defs.update(s.pop("$defs", {}))
        root_schemas[name] = s
    alias_out: dict[str, str] = {}
    for name, alias in ROOT_ALIASES.items():
        s = TypeAdapter(alias).json_schema(mode="serialization")
        defs.update(s.pop("$defs", {}))
        alias_out[name] = ts_type(s, defs)

    out: list[str] = [
        "// AUTO-GENERATED by packages/schema/codegen.py — DO NOT EDIT.",
        "// Source of truth: packages/schema/record_schema/models.py  (run `make codegen`).",
        "",
    ]
    for name, t in alias_out.items():
        out.append(f"export type {name} = {t};\n")
    emitted: set[str] = set()
    for name, s in list(defs.items()) + list(root_schemas.items()):
        if name in emitted or name in alias_out:
            continue
        emitted.add(name)
        if s.get("type") == "object" or "properties" in s:
            out.append(emit_interface(name, s, defs))
        else:
            out.append(f"export type {name} = {ts_type(s, defs)};\n")
    out.append("export const DIMENSIONS = " + json.dumps(list(rs.DIMENSIONS)) + " as const;\n")
    out.append(
        "export const DIMENSION_LABELS: Record<Dimension, Record<Lang, string>> = "
        + json.dumps(rs.DIMENSION_LABELS, ensure_ascii=False, indent=2)
        + ";\n"
    )
    text = "\n".join(out)
    text = re.sub(r"\n{3,}", "\n\n", text)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT} ({len(text)} bytes, {len(emitted)} types)", file=sys.stderr)


if __name__ == "__main__":
    main()
