// AUTO-GENERATED by packages/schema/codegen.py — DO NOT EDIT.
// Source of truth: packages/schema/record_schema/models.py  (run `make codegen`).

export type Lang = "zh-TW" | "id" | "vi" | "en";

export type ProvenanceSource = "caregiver_said" | "ai_extracted" | "nurse_assessed" | "nurse_confirmed" | "doctor_ordered" | "system_derived";

export type Dimension = "intake" | "elimination" | "function" | "cognition" | "sleep" | "skin" | "pain" | "vitals";

export type IncidentKind = "fall" | "medication_issue" | "choking" | "behavior";

export type Direction = "up" | "down" | "same" | "unknown";

export type Status = "draft" | "approved";

export type Shift = "day" | "evening" | "night";

export type RouteDecision = "contact_contract_hospital" | "home_acute_mode_b" | "accompany_visit" | "observe" | "escalate_119";

export type CareRole = "patient" | "family" | "caregiver" | "nurse" | "doctor";

export type LifeEventType = "condition" | "hospitalization" | "surgery" | "fall" | "other";

export type VerifyChoice = "with_patient" | "fine" | "maybe_injured" | "unreachable";

export type Scope = "who" | "timeline" | "docs" | "talk";

export type TimelineEntry = Observation | Incident | Encounter | Order | LifeEvent | WearableDaily;

export type Document = IncidentFile | HandoffPage | VisitPage | RoundPage | CaregiverNotes;

export interface Provenance {
  source: "caregiver_said" | "ai_extracted" | "nurse_assessed" | "nurse_confirmed" | "doctor_ordered" | "system_derived";
  author: string;
  confirmed_by: string | null;
  ts: string;
  language_original: "zh-TW" | "id" | "vi" | "en";
}

export interface DimensionValue {
  value: string | number | null;
  /** 照護者原話片段 */ raw_quote: string;
  provenance: Provenance;
  confidence: number;
  lang: "zh-TW" | "id" | "vi" | "en";
  direction: "up" | "down" | "same" | "unknown";
}

export interface FollowupQA {
  question: string;
  answer: string | null;
  answered_unknown: boolean;
  lang: "zh-TW" | "id" | "vi" | "en";
}

/** Boolean facts a caregiver can report without instruments.

Consumed by red_flags/rules.py. These are observations, not diagnoses. */
export interface ObservationFlags {
  consciousness_change: boolean;
  new_confusion_or_drowsiness: boolean;
  breathing_difficulty: boolean;
  chest_pain: boolean;
  fall_head_strike: boolean;
  cannot_get_up_after_fall: boolean;
  no_urine_24h: boolean;
  intake_sudden_drop: boolean;
  fever_feel: boolean;
}

export interface Vitals {
  temp_c: number | null;
  sbp: number | null;
  dbp: number | null;
  hr: number | null;
  rr: number | null;
  spo2: number | null;
  measured_by: string | null;
  ts: string | null;
}

export interface RedFlagHit {
  rule_id: string;
  description: string;
  facts: string[];
  action: "notify_now" | "observe";
  requires_validation: boolean;
}

export interface AllergyIntolerance {
  substance: string;
  reaction: string | null;
  severity: "mild" | "moderate" | "severe" | null;
}

export interface Condition {
  display: string;
  code: string | null;
  onset: string | null;
}

export interface Contact {
  name: string;
  relation: string;
  phone: string;
  line_user_id: string | null;
  notify_first: boolean;
}

export interface Facility {
  name: string;
  phone: string;
  contract_type: string;
}

export interface MedicationStatement {
  name: string;
  dose: string;
  schedule: string;
  is_anticoagulant: boolean;
  started: string | null;
  ordered_by: string | null;
}

export interface SensorVerification {
  choice: "with_patient" | "fine" | "maybe_injured" | "unreachable";
  text: string;
  by: string;
  ts: string;
}

export interface BaselineEntry {
  dimension: "intake" | "elimination" | "function" | "cognition" | "sleep" | "skin" | "pain" | "vitals";
  value: string | number | null;
  description: string;
  valid_from: string;
  valid_to: string | null;
  set_by: "caregiver_said" | "ai_extracted" | "nurse_assessed" | "nurse_confirmed" | "doctor_ordered" | "system_derived";
  confirmed_by: string | null;
  provenance: Provenance;
}

/** 這個人自己的正常範圍，從 timeline 的量測值算出來，不是族群常模。

`vitals_usual` 是護理師寫的一組數字；這裡是從實際量測算出來的「帶」。
兩者並存：帶只用來說明「這次跟他平常比起來如何」，
要更新 `vitals_usual` 仍必須走 ◇nurse_confirm_baseline（CLAUDE.md §1.6）。

`established=False` 時不得用來判斷任何事情——樣本太少的「正常範圍」
是誤報的主要來源，不是靈敏度不夠。 */
export interface VitalsBand {
  metric: "temp_c" | "sbp" | "dbp" | "hr" | "rr" | "spo2";
  label: string;
  unit: string;
  /** 中位數（不是平均數：生理值有離群值） */ center: number;
  /** 中位數絕對偏差 MAD（不是標準差） */ spread: number;
  /** 第 10 百分位 */ low: number;
  /** 第 90 百分位 */ high: number;
  /** 樣本數 */ n: number;
  /** 涵蓋幾天 */ days: number;
  established: boolean;
  /** established=False 時說明為什麼 */ reason: string;
  /** 給人看的一行，例如「收縮壓 129–139 mmHg」 */ text: string;
}

export interface BaselineDelta {
  domain: "intake" | "elimination" | "function" | "cognition" | "sleep" | "skin" | "pain" | "vitals";
  direction: "up" | "down" | "same" | "unknown";
  magnitude: number | null;
  days: number;
  note: string;
  evidence_refs: string[];
}

export interface MinimalSBAR {
  /** 一行 S：現況（引用照護者） */ s: string;
  /** 一行 A：只寫與基線比的變化 */ a_change_vs_baseline: string;
  status: "draft" | "approved";
  author: "ai" | "nurse";
  confirmed_by: string | null;
  nurse_edit: string | null;
}

export interface RedFlagResult {
  hits: RedFlagHit[];
  notify_now: boolean;
  observe: boolean;
  disclaimer: string;
}

export interface StructuredObservation {
  raw_text: string;
  language: "zh-TW" | "id" | "vi" | "en";
  translation_zh: string | null;
  domains: Record<string, DimensionValue>;
  seems_different: boolean;
  incident_flags: ("fall" | "medication_issue" | "choking" | "behavior")[];
  flags: ObservationFlags;
  vitals_reported: Vitals | null;
  unknown: ("intake" | "elimination" | "function" | "cognition" | "sleep" | "skin" | "pain" | "vitals")[];
  followups: FollowupQA[];
}

export interface OrderFollowUp {
  done: boolean | null;
  effective: boolean | null;
  note: string;
  evidence_refs: string[];
}

export interface OrderItem {
  text: string;
  category: "medication" | "observation" | "diet" | "activity" | "referral" | "other";
  target_dimension: "intake" | "elimination" | "function" | "cognition" | "sleep" | "skin" | "pain" | "vitals" | null;
  caregiver_instruction: string | null;
}

export interface ISBAR {
  identity: string;
  situation: string;
  background: string;
  /** AI 的 A：只寫與基線比的變化 */ ai_change_vs_baseline: string;
  /** AI 的 R：只寫請確認事項（提問式） */ ai_questions_for_nurse: string[];
  /** A — 只有護理師寫 */ nurse_assessment: string | null;
  /** R — 只有護理師寫 */ nurse_recommendation: string | null;
  status: "draft" | "approved";
  author: "ai" | "nurse";
  confirmed_by: string | null;
  confirmed_at: string | null;
}

export interface OnsiteAssessment {
  vitals: Vitals;
  consciousness: string;
  wound: string | null;
  notes: string | null;
  assessed_by: string;
  ts: string;
}

export interface CaregiverSection {
  raw_text: string;
  language: "zh-TW" | "id" | "vi" | "en";
  translation_zh: string | null;
  domains: Record<string, DimensionValue>;
  seems_different: boolean;
  incident_flags: ("fall" | "medication_issue" | "choking" | "behavior")[];
  followups: FollowupQA[];
  unknown: ("intake" | "elimination" | "function" | "cognition" | "sleep" | "skin" | "pain" | "vitals")[];
  image_summary: string | null;
  caregiver_confirmed_meaning: boolean | null;
  provenance: Provenance;
}

export interface FollowUp {
  due_at: string;
  question: string;
  answer: string | null;
  answered_at: string | null;
  set_by: string;
}

export interface Notification {
  to: "family" | "hospital" | "119" | "nurse" | "second_nurse" | "head_nurse";
  channel: "line" | "phone" | "screen";
  content: string;
  status: "draft" | "approved" | "sent" | "displayed_only";
  sent_at: string | null;
  approved_by: string | null;
  content_ref: string | null;
}

export interface NurseSection {
  onsite_assessment: OnsiteAssessment | null;
  isbar: ISBAR;
  confirmed_by: string | null;
  confirmed_at: string | null;
}

export interface SensorEvent {
  id: string;
  health_id: string;
  patient_id: string;
  ts: string;
  kind: "possible_fall";
  location: string;
  /** 加速度尖峰（g） */ accel_peak_g: number;
  /** 姿態改變（度） */ orientation_change_deg: number;
  /** 事件後靜止秒數 */ still_seconds: number;
  hr_before: number;
  hr_after: number;
  spo2_after: number | null;
  status: "pending" | "verified" | "closed";
  /** 紅燈硬條件命中（靜止 ≥ N 秒或 SpO₂ 低於門檻） */ hard_flag: boolean;
  hard_facts: string[];
  verification: SensorVerification | null;
  /** Path A thread（若已通知護理師） */ thread_id: string | null;
  source: string;
}

export interface TrendPoint {
  date: string;
  value: number | null;
  label: string;
}

export interface TrendLine {
  dimension: "intake" | "elimination" | "function" | "cognition" | "sleep" | "skin" | "pain" | "vitals";
  direction: "up" | "down" | "same" | "unknown";
  summary: string;
  window_days: number;
  magnitude: number | null;
  evidence_refs: string[];
  is_abnormal: boolean;
}

export interface TrendSeries {
  dimension: "intake" | "elimination" | "function" | "cognition" | "sleep" | "skin" | "pain" | "vitals";
  points: TrendPoint[];
}

export interface OrderFollowUpLine {
  order_id: string;
  text: string;
  done: boolean | null;
  effective: boolean | null;
  note: string;
}

export interface Baseline {
  entries: BaselineEntry[];
  vitals_usual: Vitals | null;
}

export interface CaregiverNotes {
  id: string;
  patient_id: string;
  generated_at: string;
  /** timeline ids */ generated_from: string[];
  status: "draft" | "approved";
  author: string;
  confirmed_by: string | null;
  provenance: Provenance;
  audience: "doctor" | "er" | "nurse" | "caregiver" | "family" | "system";
  doc_type: "caregiver_notes";
  lang: "zh-TW" | "id" | "vi" | "en";
  /** 本月注意三件事 */ items: string[];
  items_zh: string[];
  source_order_id: string;
}

export interface Encounter {
  id: string;
  patient_id: string;
  ts: string;
  status: "draft" | "approved";
  confirmed_by: string | null;
  provenance: Provenance;
  related_ids: string[];
  kind: "encounter";
  encounter_type: "round" | "emergency" | "visit";
  doctor: string;
  summary: string;
  order_ids: string[];
}

export interface HandoffPage {
  id: string;
  patient_id: string;
  generated_at: string;
  /** timeline ids */ generated_from: string[];
  status: "draft" | "approved";
  author: string;
  confirmed_by: string | null;
  provenance: Provenance;
  audience: "doctor" | "er" | "nurse" | "caregiver" | "family" | "system";
  doc_type: "handoff_page";
  variant: "phone_isbar" | "visit_page";
  what_happened: string;
  usual_state: string[];
  medications: string[];
  dnr: boolean;
  contacts: string[];
  isbar_text: string;
}

export interface Incident {
  id: string;
  patient_id: string;
  ts: string;
  status: "draft" | "approved";
  confirmed_by: string | null;
  provenance: Provenance;
  related_ids: string[];
  kind: "incident";
  incident_kind: "fall" | "medication_issue" | "choking" | "behavior" | "acute";
  summary: string;
  incident_file_id: string | null;
}

export interface IncidentFile {
  id: string;
  patient_id: string;
  generated_at: string;
  /** timeline ids */ generated_from: string[];
  status: "draft" | "approved";
  author: string;
  confirmed_by: string | null;
  provenance: Provenance;
  audience: "doctor" | "er" | "nurse" | "caregiver" | "family" | "system";
  doc_type: "incident_file";
  caregiver_section: CaregiverSection;
  nurse_section: NurseSection;
  red_flags: RedFlagResult | null;
  route_decision: "contact_contract_hospital" | "home_acute_mode_b" | "accompany_visit" | "observe" | "escalate_119" | null;
  notifications: Notification[];
  follow_up: FollowUp | null;
  /** 通道 4：觸發此事件的感測事件（含照護者四鍵驗證） */ sensor_event: SensorEvent | null;
}

/** 終身時間軸的大事件（年層只顯示這些＋事故）：疾病確診、住院、手術、跌倒。
來自出院摘要／病歷匯入（demo 為 seed），provenance 記來源機構。 */
export interface LifeEvent {
  id: string;
  patient_id: string;
  ts: string;
  status: "draft" | "approved";
  confirmed_by: string | null;
  provenance: Provenance;
  related_ids: string[];
  kind: "life_event";
  event_type: "condition" | "hospitalization" | "surgery" | "fall" | "other";
  title: string;
  summary: string;
  facility: string;
  ended: string | null;
}

export interface Observation {
  id: string;
  patient_id: string;
  ts: string;
  status: "draft" | "approved";
  confirmed_by: string | null;
  provenance: Provenance;
  related_ids: string[];
  kind: "observation";
  shift: "day" | "evening" | "night";
  observation: StructuredObservation;
  deltas: BaselineDelta[];
  minimal_sbar: MinimalSBAR | null;
  vitals: Vitals | null;
  red_flags: RedFlagResult | null;
}

export interface Order {
  id: string;
  patient_id: string;
  ts: string;
  status: "draft" | "approved";
  confirmed_by: string | null;
  provenance: Provenance;
  related_ids: string[];
  kind: "order";
  doctor: string;
  raw_text: string;
  items: OrderItem[];
  encounter_id: string | null;
  caregiver_notes_doc_id: string | null;
  follow_up: OrderFollowUp | null;
}

export interface Profile {
  patient_id: string;
  /** Personal Health ID（P-0000000）：紀錄屬於本人、跟著人一輩子；機構是場域之一 */ health_id: string;
  /** 代號，非真名 */ code_name: string;
  sex: "M" | "F";
  birth_year: number;
  room: string;
  conditions: Condition[];
  allergies: AllergyIntolerance[];
  medications: MedicationStatement[];
  dnr: boolean;
  emergency_contacts: Contact[];
  contract_facility: Facility;
  current_location: "facility" | "home" | "hospital";
  caregiver_code_name: string;
  caregiver_language: "zh-TW" | "id" | "vi" | "en";
  primary_nurse: string;
  /** 一句話的人 */ one_liner: string;
  height_cm: number | null;
  /** 最近一次量的體重（本人 wellness 區用） */ weight_kg: number | null;
}

/** Append-only ledger row (records/{id}/provenance.jsonl). */
export interface ProvenanceLine {
  line_id: string;
  /** timeline entry id or document id this line belongs to */ ref: string;
  /** which field inside the ref, if any */ field: string;
  source: "caregiver_said" | "ai_extracted" | "nurse_assessed" | "nurse_confirmed" | "doctor_ordered" | "system_derived";
  author: string;
  confirmed_by: string | null;
  ts: string;
  language_original: "zh-TW" | "id" | "vi" | "en";
}

export interface RoundPage {
  id: string;
  patient_id: string;
  generated_at: string;
  /** timeline ids */ generated_from: string[];
  status: "draft" | "approved";
  author: string;
  confirmed_by: string | null;
  provenance: Provenance;
  audience: "doctor" | "er" | "nurse" | "caregiver" | "family" | "system";
  doc_type: "round_page";
  /** ① 一句話的人＋基線 */ who: string;
  baseline_summary: string[];
  /** ② 異常優先 */ changes: TrendLine[];
  cross_dimension_signal: string | null;
  /** ③ */ order_followup: OrderFollowUpLine[];
  /** ④ 提問式 */ questions: string[];
  /** 變化最大的兩個維度 */ chart: TrendSeries[];
  since: string;
  page_limit_ok: boolean;
  /** 由哪個 subagent 產生、呼叫了哪些工具幾次 */ agent_note: string;
}

export interface VisitPage {
  id: string;
  patient_id: string;
  generated_at: string;
  /** timeline ids */ generated_from: string[];
  status: "draft" | "approved";
  author: string;
  confirmed_by: string | null;
  provenance: Provenance;
  audience: "doctor" | "er" | "nurse" | "caregiver" | "family" | "system";
  doc_type: "visit_page";
  reason: string;
  recent: string[];
  medications: string[];
}

/** 通道 4 穿戴每日指標（模擬）。只有事實數值，不存任何品質分數；照護鏈只把心率／SpO₂ 當觀察事實。
資料形狀參考 health-ref 的 daily_metrics（想法，重新設計）。 */
export interface WearableDaily {
  id: string;
  patient_id: string;
  ts: string;
  status: "draft" | "approved";
  confirmed_by: string | null;
  provenance: Provenance;
  related_ids: string[];
  kind: "wearable_daily";
  day: string;
  steps: number;
  exercise_min: number;
  resting_hr: number;
  hrv_ms: number;
  spo2: number;
  sleep_hours: number;
  deep_sleep_hours: number;
  rem_hours: number;
  source: string;
}

export interface CareCircleMember {
  health_id: string;
  /** 身份代號（cg_xiaofang、nurse_lin、fam_P001、P001…） */ member_id: string;
  name: string;
  role: "patient" | "family" | "caregiver" | "nurse" | "doctor";
  /** 可見範圍：who|timeline|docs|talk 子集 */ scopes: ("who" | "timeline" | "docs" | "talk")[];
  valid_from: string;
  valid_to: string | null;
  /** 誰授權（本人或代理） */ granted_by: string;
  revoked_at: string | null;
}

export interface AccessLogEntry {
  health_id: string;
  who: string;
  role: "patient" | "family" | "caregiver" | "nurse" | "doctor" | null;
  /** 看了什麼（who|timeline|docs|talk|summary|ask…） */ what: string;
  ts: string;
}

export interface BaselineProposal {
  patient_id: string;
  proposals: BaselineEntry[];
  reason: string;
  status: "draft" | "approved";
  proposed_by: "caregiver_said" | "ai_extracted" | "nurse_assessed" | "nurse_confirmed" | "doctor_ordered" | "system_derived";
  confirmed_by: string | null;
  source_order_id: string | null;
}

/** 一位住民的所有生理值正常帶。系統推導，不寫入 baseline。 */
export interface VitalsBands {
  patient_id: string;
  computed_at: string;
  window_days: number;
  bands: Record<string, VitalsBand>;
}

export interface TimelineBase {
  id: string;
  patient_id: string;
  ts: string;
  status: "draft" | "approved";
  confirmed_by: string | null;
  provenance: Provenance;
  related_ids: string[];
}

export interface DocBase {
  id: string;
  patient_id: string;
  generated_at: string;
  /** timeline ids */ generated_from: string[];
  status: "draft" | "approved";
  author: string;
  confirmed_by: string | null;
  provenance: Provenance;
  audience: "doctor" | "er" | "nurse" | "caregiver" | "family" | "system";
}

export interface TrendReport {
  patient_id: string;
  since: string;
  until: string;
  lines: TrendLine[];
  cross_dimension_signal: string | null;
  series: TrendSeries[];
  incident_ids: string[];
  generated_by: "caregiver_said" | "ai_extracted" | "nurse_assessed" | "nurse_confirmed" | "doctor_ordered" | "system_derived";
}

export interface PersonRecord {
  profile: Profile;
  baseline: Baseline;
  timeline: (Observation | Incident | Encounter | Order | LifeEvent | WearableDaily)[];
  documents: (IncidentFile | HandoffPage | VisitPage | RoundPage | CaregiverNotes)[];
  provenance: ProvenanceLine[];
}

export const VERIFY_LABELS: Record<VerifyChoice, string> = {"with_patient": "我在他身邊", "fine": "他沒事", "maybe_injured": "他可能受傷", "unreachable": "聯絡不上"};

export const DIMENSIONS = ["intake", "elimination", "function", "cognition", "sleep", "skin", "pain", "vitals"] as const;

export const DIMENSION_LABELS: Record<Dimension, Record<Lang, string>> = {
  "intake": {
    "zh-TW": "進食與飲水",
    "id": "Makan & minum",
    "vi": "Ăn uống",
    "en": "Intake"
  },
  "elimination": {
    "zh-TW": "排泄",
    "id": "Buang air",
    "vi": "Bài tiết",
    "en": "Elimination"
  },
  "function": {
    "zh-TW": "活動與日常功能",
    "id": "Aktivitas",
    "vi": "Vận động",
    "en": "Function"
  },
  "cognition": {
    "zh-TW": "意識、認知、情緒、溝通",
    "id": "Kesadaran & emosi",
    "vi": "Ý thức & cảm xúc",
    "en": "Cognition"
  },
  "sleep": {
    "zh-TW": "睡眠",
    "id": "Tidur",
    "vi": "Giấc ngủ",
    "en": "Sleep"
  },
  "skin": {
    "zh-TW": "皮膚與傷口",
    "id": "Kulit & luka",
    "vi": "Da & vết thương",
    "en": "Skin"
  },
  "pain": {
    "zh-TW": "疼痛",
    "id": "Nyeri",
    "vi": "Đau",
    "en": "Pain"
  },
  "vitals": {
    "zh-TW": "生命徵象與呼吸症狀",
    "id": "Tanda vital & napas",
    "vi": "Sinh hiệu & hô hấp",
    "en": "Vitals"
  }
};
